# Generated by Django 5.1.3 on 2024-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nohp', models.IntegerField()),
                ('tgl_join', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_id', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('durasi', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nohp', models.IntegerField()),
                ('tgl_join', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaksi_id', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
                ('trainer_id', models.CharField(max_length=100)),
                ('tgl_transaksi', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
